config/routes.rb
KnittingApp::Application.routes.draw do

  resources :patterns do
    member do
      put "like_show", to: "patterns#like_show"
      put "unlike_show", to: "patterns#unlike_show"
      put "like_index", to: "patterns#like_index"
      put "unlike_index", to: "patterns#unlike_index"
    end
    collection do
      get :popular
      get :ladies
      get :gents
      get :kids
      get :babies
      get :holiday
      get :easy
      get :intermediate
      get :advanced
    end
  end

  get "patterns/:id", to: "patterns#pdf", as: 'pdf'
 
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :comments, :only => [:create, :destroy, :show]

  resources :categories

  resources :stitches

  resources :rows

  resources :users

  get "users/:id/likes", to: "users#likes", as: 'user_likes'

  authenticated do
  root :to => 'patterns#index', as: :authenticated
  end

  root :to => 'static#index'

end

app/models/stitch.rb
class Stitch < ActiveRecord::Base
  belongs_to :row, touch: true
  attr_accessible :color, :position, :stitch_symbol, :row_id
end

app/controllers/stitches_controller.rb
class StitchesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /stitches
  # GET /stitches.json
  def index
    @stitches = Stitch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stitches }
    end
  end

  # GET /stitches/1
  # GET /stitches/1.json
  def show
    @stitch = Stitch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stitch }
    end
  end

  # GET /stitches/new
  # GET /stitches/new.json
  def new
    @stitch = Stitch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stitch }
    end
  end

  # GET /stitches/1/edit
  def edit
    @stitch = Stitch.find(params[:id])
  end

  # POST /stitches
  # POST /stitches.json
  def create
    @stitch = Stitch.new(params[:stitch])

    respond_to do |format|
      if @stitch.save
        format.html { redirect_to @stitch, notice: 'Stitch was successfully created.' }
        format.json { render json: @stitch, status: :created, location: @stitch }
      else
        format.html { render action: "new" }
        format.json { render json: @stitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stitches/1
  # PUT /stitches/1.json
  def update
    @stitch = Stitch.find(params[:id])

    respond_to do |format|
      if @stitch.update_attributes(params[:stitch])
        format.html { redirect_to @stitch, notice: 'Stitch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stitches/1
  # DELETE /stitches/1.json
  def destroy
    @stitch = Stitch.find(params[:id])
    @stitch.destroy

    respond_to do |format|
      format.html { redirect_to stitches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stitches_helper.rb
module StitchesHelper
end

app/views/stitches/_form.html.haml
= simple_form_for @stitch do |f|
  - if @stitch.errors.any?
    #error_explanation
      %h2= "#{pluralize(@stitch.errors.count, "error")} prohibited this stitch from being saved:"
      %ul
        - @stitch.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :color
    = f.text_field :color
  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :position
    = f.number_field :position
  .actions
    = f.submit 'Save'

app/views/stitches/edit.html.haml
%h1 Editing stitch

= render 'form'

= link_to 'Show', @stitch
\|
= link_to 'Back', stitches_path

app/views/stitches/index.html.haml
%h1 Listing stitches

%table
  %tr
    %th Row
    %th Color
    %th Type
    %th Position
    %th
    %th
    %th

  - @stitches.each do |stitch|
    %tr
      %td= stitch.row
      %td= stitch.color
      %td= stitch.type
      %td= stitch.position
      %td= link_to 'Show', stitch
      %td= link_to 'Edit', edit_stitch_path(stitch)
      %td= link_to 'Destroy', stitch, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Stitch', new_stitch_path

app/views/stitches/new.html.haml
%h1 New stitch

= render 'form'

= link_to 'Back', stitches_path

app/views/stitches/show.html.haml
%p#notice= notice

%p
  %b Row:
  = @stitch.row
%p
  %b Color:
  = @stitch.color
%p
  %b Type:
  = @stitch.type
%p
  %b Position:
  = @stitch.position

= link_to 'Edit', edit_stitch_path(@stitch)
\|
= link_to 'Back', stitches_path