config/routes.rb
KnittingApp::Application.routes.draw do

  resources :patterns do
    member do
      put "like_show", to: "patterns#like_show"
      put "unlike_show", to: "patterns#unlike_show"
      put "like_index", to: "patterns#like_index"
      put "unlike_index", to: "patterns#unlike_index"
    end
    collection do
      get :popular
      get :ladies
      get :gents
      get :kids
      get :babies
      get :holiday
      get :easy
      get :intermediate
      get :advanced
    end
  end

  get "patterns/:id", to: "patterns#pdf", as: 'pdf'
 
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :comments, :only => [:create, :destroy, :show]

  resources :categories

  resources :stitches

  resources :rows

  resources :users

  get "users/:id/likes", to: "users#likes", as: 'user_likes'

  authenticated do
  root :to => 'patterns#index', as: :authenticated
  end

  root :to => 'static#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter

  has_many :images
  has_many :patterns
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, omniauth_providers: [:google_oauth2]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :membership, :name, :user_image, :role, :description, :uid, :provider

  mount_uploader :user_image, UserImageUploader
  before_validation :set_role_to_registered


  def role?(role_to_compare)
    role.to_s == role_to_compare.to_s
  end 

  
def self.from_omniauth(auth)
  if user = User.find_by_email(auth.info.email)
    user.provider = auth.provider
    user.uid = auth.uid
    user
  else
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

  private
  def set_role_to_registered
    self.role ||= "registered"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @user_likes = current_user.find_liked_items

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :user_image
    = f.file_field :user_image
  .field
    = f.label :description
    %br
    = f.text_area :description
  .actions
    = f.submit 'Save', class: 'btn'
    %br

app/views/users/_img_form.html.haml
= form_for @user do |f|
  .field
    = f.label :user_image
    = f.file_field :user_image
  .actions
    = f.submit 'Save'

app/views/users/_likes.html.haml
- @user_likes.each do |pattern|
  .pattern_card
    .pattern_preview
      - pattern.rows[0..7].each do |row|
        .pattern_row{ id: row.id }
          - row.stitches[0..11].each do |stitch|
            .stitch{ :style => "color: #{stitch.color}", :data => { id: stitch.id} } 
              - if stitch.stitch_symbol.strip.empty?
                &nbsp;
              - else
                =raw stitch.stitch_symbol.strip
    .pattern_description_index
      %p= link_to pattern.name, pattern
      .pattern_description_likes
        = link_to like_index_pattern_path(pattern), method: :put do
          %i.fa.fa-heart
        - if pattern.likes.size > 0
          = pattern.likes.size
      .pattern_description_img
        - if pattern.user.user_image.file && pattern.user.user_image.file.exists?
          = link_to(image_tag(pattern.user.user_image.thumb.url), user_path(pattern.user_id))
        - else
          = link_to image_tag("default-avatar-thumb.png"), user_path(pattern.user_id)
      .pattern_details
        %p= pattern.user.try(:name)
        %p= "#{pattern.difficulty.try(:name)}, #{pattern.category.try(:name)}"

app/views/users/_private_profile.html.haml
- @user.patterns.each do |pattern|
  .pattern_card
    .pattern_preview
      - pattern.rows[0..7].each do |row|
        .pattern_row{ id: row.id }
          - row.stitches[0..11].each do |stitch|
            .stitch{ :style => "color: #{stitch.color}", :data => { id: stitch.id} }
              - if stitch.stitch_symbol.strip.empty?
                &nbsp;
              - else
                =raw stitch.stitch_symbol.strip
    .pattern_description_index
      %p= link_to pattern.name, pattern
      .pattern_description_likes
        = link_to like_index_pattern_path(pattern), method: :put do
          %i.fa.fa-heart
        - if pattern.likes.size > 0
          = pattern.likes.size
      .pattern_description_img
        - if pattern.user.user_image.file && pattern.user.user_image.file.exists?
          = link_to(image_tag(pattern.user.user_image.thumb.url), user_path(pattern.user_id))
        - else
          = link_to image_tag("default-avatar-thumb.png"), user_path(pattern.user_id)
      .pattern_details
        %p= pattern.user.try(:name)
        %p= "#{pattern.difficulty.try(:name)}, #{pattern.category.try(:name)}"

app/views/users/_public_profile.html.haml
- @user.patterns.each do |pattern|
  - if pattern.status == "public"
    .pattern_card
      .pattern_preview
        - pattern.rows[0..6].each do |row|
          .pattern_row{ id: row.id }
            - row.stitches[0..11].each do |stitch|
              .stitch{ :style => "color: #{stitch.color}", :data => { id: stitch.id} }
                - if stitch.stitch_symbol.strip.empty?
                  &nbsp;
                - else
                  =raw stitch.stitch_symbol.strip
      .pattern_description_index
        %p= link_to pattern.name, pattern
        .pattern_description_likes
          = link_to like_index_pattern_path(pattern), method: :put do
            %i.fa.fa-heart
          - if pattern.likes.size > 0
            = pattern.likes.size
        .pattern_description_img
          - if pattern.user.user_image.file && pattern.user.user_image.file.exists?
            = link_to(image_tag(pattern.user.user_image.thumb.url), user_path(pattern.user_id))
          - else
            = link_to image_tag("default-avatar-thumb.png"), user_path(pattern.user_id)
        .pattern_details
          %p= pattern.user.try(:name)
          %p= "#{pattern.difficulty.try(:name)}, #{pattern.category.try(:name)}"

app/views/users/edit.html.haml
.main
  %h1 Account Settings

  = render 'form'

  = link_to 'Cancel', user_path(@user)

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th User image
    %th Membership
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.user_image
      %td= user.membership
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/likes.html.haml
.main
  - @user_likes.each do |pattern|
    .pattern_card
      .pattern_preview
        - pattern.rows[0..6].each do |row|
          .pattern_row{ id: row.id }
            - row.stitches[0..11].each do |stitch|
              .stitch{ :style => "background-color: #{stitch.color}", :data => { id: stitch.id} }
      .pattern_description_index
        %p= link_to pattern.name, pattern
        = link_to like_index_pattern_path(pattern), method: :put do
          %i.fa.fa-heart
        - if pattern.likes.size > 0
          = pattern.likes.size
        %p= link_to(image_tag(pattern.user.user_image.thumb.url), user_path(pattern.user_id))
        %p= pattern.user.try(:name)
        %p= pattern.difficulty.try(:name)
        %p= pattern.category.try(:name)

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
.main
  %p#notice= notice

  .profile
    .profile_img
      - if @user.user_image.file && @user.user_image.file.exists?
        = image_tag(@user.user_image.profile.url)
      - else
        = image_tag("default-avatar.png")
      = link_to 'Change image', edit_user_path(@user), class: 'hidden', id: 'edit_img'
    .profile_details
      %h2= @user.name
      %p= @user.description

  #tabs.profile
    %ul
      %li
        %a{:href => "#tabs-1"} Patterns
      %li
        %a{:href => "#tabs-2"} Likes
    #tabs-1
      #container
        - if current_user == @user
          = render 'private_profile'
        - else
          = render 'public_profile'
    #tabs-2
      #container
        - @user_likes.each do |pattern|
          = render 'likes'