config/routes.rb
KnittingApp::Application.routes.draw do

  resources :patterns do
    member do
      put "like_show", to: "patterns#like_show"
      put "unlike_show", to: "patterns#unlike_show"
      put "like_index", to: "patterns#like_index"
      put "unlike_index", to: "patterns#unlike_index"
    end
    collection do
      get :popular
      get :ladies
      get :gents
      get :kids
      get :babies
      get :holiday
      get :easy
      get :intermediate
      get :advanced
    end
  end

  get "patterns/:id", to: "patterns#pdf", as: 'pdf'
 
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :comments, :only => [:create, :destroy, :show]

  resources :categories

  resources :stitches

  resources :rows

  resources :users

  get "users/:id/likes", to: "users#likes", as: 'user_likes'

  authenticated do
  root :to => 'patterns#index', as: :authenticated
  end

  root :to => 'static#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Knitsy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- <meta name="viewport" content="width=device-width; initial-scale=1.0"> -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Sniglet' rel='stylesheet' type='text/css'>

</head>
<body>

  <!-- navbar -->
  <nav>
    <ul class="fluid_container">
      <% if current_user %>
        <li id="filter_button"><span class="glyphicon glyphicon-th-list"></span></li>
        <li id="search_form" class="hidden">
          <%= search_form_for @q do |f| %>
            <%= f.text_field :name_or_description_cont, placeholder: 'Search' %>
            <%= f.submit "Search" %>
          <% end %>
        </li>
        <li id="logo"><%= link_to 'knitsy', patterns_path %></li>
        <li id="add_pattern"><%= link_to '', new_pattern_path, id: 'new_pattern' %>
          <div id="pattern_form">
            <%= render 'shared/new_pattern_form' %>
          </div>
        </li>
        <li id="profile_button"><%= current_user.name %></li>
      <% else %>
        <li id="sign_up"><%= link_to 'SIGN UP', new_user_registration_path %></li>
        <li id="login"><%= link_to 'LOGIN', new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
  <!--   content -->
  
  <%= yield %>


  <div id="filter" class="hidden filter_options">
    <ul>
      <li><%= link_to "Popular", popular_patterns_path %></li>
      <li><%= link_to "Women's", ladies_patterns_path %></li>
      <li><%= link_to "Men's", gents_patterns_path %></li>
      <li><%= link_to "Kids", kids_patterns_path %></li>
      <li><%= link_to "Babies", babies_patterns_path %></li>
      <li><%= link_to "Holiday", holiday_patterns_path %></li>
      <li><%= link_to "Easy", easy_patterns_path %></li>
      <li><%= link_to "Intermediate", intermediate_patterns_path %></li>
      <li><%= link_to "Advanced", advanced_patterns_path %></li>
    </ul>
  </div>
  <% if current_user %>
    <div id="profile" class="hidden profile_options">
      <ul>
        <li><%= link_to 'Your profile', user_path(current_user.id) %></li>
        <li><%= link_to 'Settings', edit_user_path(current_user.id) %></li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  <% end %>

</body>
</html>